package playtime
/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
import java.nio.charset.StandardCharsets
import java.nio.file.Paths
import java.nio.file.Files
import java.nio.file.Path




class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {

        URL url = App.class.getResource("/input_data.txt")
        Path path = Paths.get(url.toURI());
        
        List<String> lines = Files.readAllLines(path, StandardCharsets.UTF_8)
        println "${lines}"
        
        
    }
}
