/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package playtime

class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        println new App().greeting
        def ars = ["key" : "data"]
        ars.newKey = "This"
        println "${ars.keySet()} ${ars.newKey} - the data"
        
        
        
    }
}
